Feature/merge
Japan-DfinityInfoHub/portal pull request #21
Opened 2022-10-29 23:21 UTC by hokosugi

コンフリクトをしていたのは以下の８つのファイルです。（一番上は隠しファイルでaddしたときに強制 `-f` のオプションをつけろと言われたので add しておりません。ですので計７つになります。）
hint: Use -f if you really want to add them.

* both modified:   .vscode/settings.json
* both modified:   docs/samples/overview.md
* both modified:   docs/tokenomics/identity-auth/what-is-ic-identity.md
* both modified:   what-is-the-ic/1_ic/index.md
* both modified:   what-is-the-ic/2_nns/index.md
* both modified:   what-is-the-ic/3_canisters/index.md
* both modified:   what-is-the-ic/4_consensus/index.md
* both modified:   what-is-the-ic/5_chain-key/index.md

初めてですので、まだ要領が分かっておりません。間違っているところが多数と思います。ご面倒ですが、確認していただき、修正をお願いします。

2022-10-30 02:44 UTC, hoosan requested changes
ご対応ありがとうございます🙏
変更ファイル数が多くVSCode上ではなかなかdiffが見つけづらいですので、PRを見ると修正されていた箇所が確認できると思います。
（自分がやる時も、一旦PRを出してWIP状態にし、diffを見ながら修正しています）

直接コメント付けた箇所もありますが、それ以外で気づいた変更ファイルとしては以下です。（画像で失礼します）

- docs/developer-docs/quickstart/hello10mins.md
- docs/developer-docs/quickstart/local-quickstart.md
- docs/developer-docs/quickstart/hello20mins.md
- docs/developer-docs/quickstart/network-quickstart.md

https://smartcontracts.org/install.sh を https://internetcomputer.org/install.sh に

- [docs/samples/encrypted-notes.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-8493bdbeb17303bfc2a5c75dc8dfbdece058cf22cd1c92a8d3a618b750b8168f)

![image](https://user-images.githubusercontent.com/40290137/198859694-8b1b5def-57c0-4dcb-b10c-bcda2409e13d.png)

- [docs/tokenomics/identity-auth/auth-how-to.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-26f49672641e2c8e310afdc9f15f1515e3432441cc35e04c555822f18b91a49a)

![image](https://user-images.githubusercontent.com/40290137/198859709-9d95b4fb-82ba-4401-8184-3b1c7108657f.png)

- [docs/tokenomics/identity-auth/what-is-ic-identity.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-9eb64b13b59952cd7ac93f46bb08110edeff49017966104e031d4db1eb96ade9)

![image](https://user-images.githubusercontent.com/40290137/198859721-8afd5441-8962-437d-85f6-92aebc62cc89.png)

[what-is-the-ic/5_chain-key/index.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-ce785e173356f952c3eac9d79ccc0a929ed7db0babebfd4bfdff0321b047e398)

![image](https://user-images.githubusercontent.com/40290137/198860085-58a5f467-cd14-480e-b0e1-19a519dbb8d6.png)

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/2_nns/index.md
> +また、ICP トークンのステークホルダーは、ICP のあらゆる側面に関する投票に参加することができます。例えば、ステークホルダーは、IC ソフトウェアのアップグレードや、新しいサブネットの追加などによる IC の拡張に関して投票することが可能です（ステーク、投票、報酬の詳細は[こちら](https://wiki.internetcomputer.org/wiki/Staking,_voting_
リンク先が違っているようです
```suggestion
また、ICP トークンのステークホルダーは、ICP のあらゆる側面に関する投票に参加することができます。例えば、ステークホルダーは、IC ソフトウェアのアップグレードや、新しいサブネットの追加などによる IC の拡張に関して投票することが可能です（ステーク、投票、報酬の詳細は[こちら](https://internetcomputer.org/how-it-works/network-nervous-system-nns/)を御覧ください）。また、分散型アプリの実行時に消費される ICP トークンを Cycle に変換することで、IC 上の演算する動力になります。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/2_nns/index.md
>  NNSは、世界で最も先進的な分散型自律組織（DAO）なのです。NNS の詳細は[こちら](https://internetcomputer.org/how-it-works/network-nervous-system-nns/)をご覧ください。
こちらも修正必要です
```suggestion
NNSは、世界で最も先進的な分散型自律組織[（DAO）](/docs/current/tokenomics/#network-nervous-system-nns)なのです。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/3_canisters/index.md
>  - ブロックチェーンから直接ユーザーインターフェースを提供できます。
こちらに対応するdiffが反映されていないようです
（7行目：スマートコントラクトとは・・以降）
```diff
- A smart contract is a computer program executed on a blockchain. A *canister*, or canister smart contract, is a bundle comprising a computer program and its data. Every canister is hosted on one subnet of the IC.
+ A smart contract is a computer program executed on a blockchain. A canister is a smart contract that bundles a computer program and its data. Every canister is hosted on one subnet of the IC.
+ Canisters can be executed concurrently and communicate within and across subnets by sending asynchronous messages in a non-blocking manner, resulting in essentially unbounded scalability.
+ Canisters are more powerful than smart contracts on other blockchains as they can
```

また、13行目は `-` から `*` に変更されています
```suggestion
* ブロックチェーンから直接ユーザーインターフェースを提供できます。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/3_canisters/index.md
>  - 低料金で数ギガバイトのメモリを保持することができ、低コストで相当量の演算を実行し、演算相応額を自身で支払うことができます（[リバースガス・モデル](https://internetcomputer.org/features/reverse-gas/)を御覧ください）。
こちらも変更されております
```suggestion
* 低料金で数ギガバイトのメモリを保持することができます。
* 低コストで相当量の演算を実行することができます。
* 演算相応額を自身で支払うことができます（[リバースガス・モデル](https://internetcomputer.org/features/reverse-gas/)を御覧ください）。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/4_consensus/index.md
>  - 低いレイテンシー - 少ないラウンド数の交換で合意に達します。通常、1～2秒以内にコンセンサスに到達します。
`-` から `*` への変更です
 ```suggestion
* 低いレイテンシー - 少ないラウンド数の交換で合意に達します。通常、1～2秒以内にコンセンサスに到達します。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/4_consensus/index.md
>  - 高いスループット - すべてのコンセンサス実行は、メガバイトオーダーのペイロードを処理することができます。
```suggestion
* 高いスループット - すべてのコンセンサス実行は、メガバイトオーダーのペイロードを処理することができます。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/4_consensus/index.md
>  - 暗号学的なファイナリティ - IC コンセンサスは暗号学的に保証されたファイナリティに達します。すなわち、確定したステートの変更は元に戻すことができません。
```suggestion
* 暗号学的なファイナリティ - IC コンセンサスは暗号学的に保証されたファイナリティに達します。すなわち、確定したステートの変更は元に戻すことができません。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/4_consensus/index.md
> +- ビザンチンフォールトトレランス（BFT） - 任意の1/3まで（ただし、それ以下）の欠陥ノードを許容することができます。
```suggestion
* ビザンチンフォールトトレランス（BFT） - 任意の1/3まで（ただし、それ以下）の欠陥ノードを許容することができます。
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/5_chain-key/index.md
>  - サブネットのステート
```suggestion
* ユーザーのリクエストに対するレスポンス
* サブネットのステート
```

2022-10-30 02:44 UTC, hoosan commented on what-is-the-ic/5_chain-key/index.md
> +- 完全な分散型サブネット間メッセージ
```suggestion
* 完全な分散型サブネット間メッセージ
```

2022-10-30 07:26 UTC, hokosugi commented
すべてコミットしました。ありがとうございます。
質問です。以下のファイルが変更があったとのことですが、
- docs/developer-docs/quickstart/hello10mins.md
- docs/developer-docs/quickstart/local-quickstart.md
- docs/developer-docs/quickstart/hello20mins.md
- docs/developer-docs/quickstart/network-quickstart.md

これらはdiscordで教えてもらった、コンフリクトを修正し、
> Unmerged pathsとしてwhat-is-ic-identityが赤くなっているので、コミットします。
をする以外にも、修正しないといけないところがある、つまり、
> 残りのファイルはAuto-mergingできているのですが、翻訳済みのファイルに対して原文の修正があった場合、可能な限り日本語訳も修正しておくのが良いです。今回ですとリンク先が変わっているファイルがあるので、個別に修正してコミットします
ということで、「Unmerged pathsとしてwhat-is-ic-identityが赤くなっている・・・」作業以外にもすることがあるということでよろしいですか？
また、上記のリストと画像のファイル名がマッチしないのですが、これはまた別の修正点なのでしょうか？

宜しくおねがいします。

2022-10-30 10:09 UTC, hoosan commented
## コンフリクトを修正する以外にも修正箇所がある

ご認識の通りです🙏

docs/developer-docs/quickstart/hello10mins.md
docs/developer-docs/quickstart/local-quickstart.md
docs/developer-docs/quickstart/hello20mins.md
docs/developer-docs/quickstart/network-quickstart.md

これらのファイルに関しては、リンク先が変わっているファイルがあるので、個別に修正してコミットいただきたいです。

## リストと画像のファイル名がマッチしない

説明不足ですみません、修正箇所のdiffの参考のつもりで貼っておりました（画像のファイル名はランダムです）

![image](https://user-images.githubusercontent.com/40290137/198873024-41575463-e575-41b9-8d4e-e65d8c5bcc3b.png)

以下のリンク先を見ていただくと、
[what-is-the-ic/5_chain-key/index.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-ce785e173356f952c3eac9d79ccc0a929ed7db0babebfd4bfdff0321b047e398)

下の画像のように、そのファイルのdiffが青枠で囲まれていると思います。
![image](https://user-images.githubusercontent.com/40290137/198873080-acf5e31d-54d5-4b66-9697-245eb76e2ffe.png)

青枠内のdiffを見ていただくと、今回のPRで原文のどこに修正があったか確認することができますので、原文の修正箇所を見ながら日本語訳を修正いただき、コミットしていただければと思います。

以下、原文に修正があったため日本語訳を修正いただきたいファイルのリストです
[docs/samples/encrypted-notes.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-8493bdbeb17303bfc2a5c75dc8dfbdece058cf22cd1c92a8d3a618b750b8168f)
[docs/tokenomics/identity-auth/auth-how-to.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-26f49672641e2c8e310afdc9f15f1515e3432441cc35e04c555822f18b91a49a)
[what-is-the-ic/5_chain-key/index.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-ce785e173356f952c3eac9d79ccc0a929ed7db0babebfd4bfdff0321b047e398)
[docs/tokenomics/identity-auth/what-is-ic-identity.md](https://github.com/Japan-DfinityInfoHub/portal/pull/21/files#diff-9eb64b13b59952cd7ac93f46bb08110edeff49017966104e031d4db1eb96ade9)

2022-10-31 11:12 UTC, hokosugi commented
ご指摘の8ファイルを変更しました。
たぶん、漏れはないと思いますが、ご確認ください。
`5_chain-key/index.md`の
「従来のブロックチェーンは通常、新たに参加した当事者がチェーン上で行われたすべての取引を再検証する必要があります、特に IC のような高スループットのシステムでは実現不可能でした。」
が適当か判断お願いします。

2022-11-01 04:31 UTC, hoosan requested changes
ご対応ありがとうございます🙏nitsですがいくつか細かいsuggestionを付けましたのでご確認お願いします

2022-11-01 04:31 UTC, hoosan commented on what-is-the-ic/2_nns/index.md
> +[Network Nervous System（NNS）](/how-it-works/network-nervous-system-nns/)は、IC 全体の構造に関する真実を伝える分散型の情報源で、すべてのノードとそのサブネットへの割り当てに関する情報を保存しています。
[信頼できる唯一の情報源](https://ja.wikipedia.org/wiki/%E4%BF%A1%E9%A0%BC%E3%81%A7%E3%81%8D%E3%82%8B%E5%94%AF%E4%B8%80%E3%81%AE%E6%83%85%E5%A0%B1%E6%BA%90)がテクニカルタームとしては適切かと思います
```suggestion
[Network Nervous System（NNS）](/how-it-works/network-nervous-system-nns/)は、IC 全体の構造に関する分散型の、信頼できる唯一の情報源で、すべてのノードとそのサブネットへの割り当てに関する情報を保存しています。
```

2022-11-01 04:31 UTC, hoosan commented on what-is-the-ic/4_consensus/index.md
> +Internet Computer Protocol は、サブネットの複数のノード（最大で3分の1以下）が故障したり誤動作したりしても、どのサブネットの Canister ステートが辻褄が合うことを保証するものです。ICはプルーフ・オブ・ワークでもプルーフ・オブ・ステークでもなく、いわゆる *DAO-controlled network* であり、NNS DAO がサブネットノードのメンバーシッ
（最大で3分の1以下）の記載がなくなっているのと、日本語しては元のものの方が自然に感じました
```suggestion
Internet Computer Protocol は、サブネットの複数のノードが故障したり誤動作したりしても、サブネットのどのノードも常に同じ Canister のステートを保持することを保証するものです。ICはプルーフ・オブ・ワークでもプルーフ・オブ・ステークでもなく、いわゆる *DAO-controlled network* であり、NNS DAO がサブネットノードのメンバーシップを管理します。
```

2022-11-01 04:31 UTC, hoosan commented on what-is-the-ic/5_chain-key/index.md
> +従来のブロックチェーンは通常、新たに参加した当事者がチェーン上で行われたすべての取引を再検証する必要があります、特に IC のような高スループットのシステムでは実現不可能でした。
which節ですが、日本語としては文を切っても問題ない（その方が読みやすい）と思います
```suggestion
従来のブロックチェーンは通常、新たに参加した当事者がチェーン上で行われたすべての取引を再検証する必要があります。これは IC のような高スループットのシステムでは実現不可能でした。
```

2022-11-01 12:55 UTC, hokosugi commented
いろいろありがとうございました。
今回は初めてということもあり、またgitの扱い方がまだ慣れていなくて、実は何度もやり直しましたｗ
本家への追従は溜めると大変そうなので、今後は定期的に巡回して追従するようにします！！

2022-11-02 01:51 UTC, hoosan approved these changes

2022-11-02 01:51 UTC, merged