Feature/merge
Japan-DfinityInfoHub/portal pull request #28
Opened 2022-11-17 11:45 UTC by hokosugi

## Dfinity 本家を追随するためのプルリク

お騒がせしました。
今から差分を見つつ、コミットしていきます。

2022-11-17 12:56 UTC, hokosugi commented
翻訳済みのファイルは、
* docs/samples/nft.md
* docs/developer-docs/integrations/index.md

のみ確認しました。
docs/samples/nft.mdはスペルミスの修正（129行）だけなので翻訳修正の必要はありません。
docs/developer-docs/integrations/index.mdは３行目後半から１３行目が新たに翻訳した箇所になります。

その他に修正するファイルは"files changed"で差分を目視で確認しましたがなかったと思います。
漏れがあるかも知れません。ご確認ください。もし、目視以外に検索出来るようでしたらお教えくださると幸いです。

2022-11-17 14:20 UTC, hoosan requested changes
ありがとうございます、概ね問題ございません。
いくつかコメントつけましたのでご確認いただけますと幸いです🙏

しかし、how-it-works以下はこう勢いよく修正されると翻訳の手を出しにくいですね。
技術的な部分をしっかり勉強できるdeveloper-docsに対象を絞っても良いような気がしました（現状すでにそうしていただいてますが）

2022-11-17 14:20 UTC, hoosan commented on docs/developer-docs/integrations/index.md
>  * [hotkeys](./rosetta/hotkeys.md) explains how to generate a hotkey for neuron management
ここのコメントアウトの閉じがなくエラーになっているようです
```suggestion
* [hotkeys](./rosetta/hotkeys.md) explains how to generate a hotkey for neuron management]

-->
```

2022-11-17 14:20 UTC, hoosan commented on docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile.md
> +    ```
お手数ですがこちらに関しても日本語の方修正お願いします🙏

2022-11-17 22:24 UTC, hokosugi commented
ふたつともコミットしました。心配な点もあるのでフローを記しておきます。

* `docs/developer-docs/integrations/index.md` をそのままコミット（コミットナンバー86d4457597b7ce0e84b4a5140407ad205845e294）
* ローカルで `docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile.md`を修正後、push。しかし、non-fast-forwardでrejectされたので
    * git fetch
    * git merge origin/feature/merge
で再度pushしました。

これでちゃんと反映できているか確認お願いします。

2022-11-18 23:34 UTC, hoosan approved these changes

2022-11-18 23:34 UTC, merged